PUT https://guarded-sea-44956.herokuapp.com/api/persons/1
Content-Type: application/json

{
  "id": 1,
  "name": "Arto Hellas",
  "number": "040-12345622"
}


###

PUT http://localhost:3001/api/persons/1
Content-Type: application/json

{
  "id": 1,
  "name": "Arto Hellas",
  "number": "040-123456223"
}